name: Close a PagerDuty Maintenance Window
description: Closes the specified PagerDuty maintenance window.

inputs:
  pagerduty-api-key:
    description: 'The PagerDuty API Key that allows access to your services'
    required: true
  maintenance-window-id:
    description: 'The ID of the maintenance window to be closed.' 
    required: true
  minutes:
    description: 'The number of minutes to close the window in.  Defaults to 3.  Must be greater than 0.'
    required: true
    default: '3'

runs:
  using: 'node16'
  main: 'dist/index.js'
